### ISSUE TITLE
Bruh. Какой то дикий уровень вложенности 

### ISSUE THREAD

**Issue by RB387** [glasgo-seven/Kotlin_TicTacToe#1]
https://github.com/glasgo-seven/Kotlin_TicTacToe/blob/8398c0449dfa86b6bbe1c06db7731ef58cfdfe76/AI.kt#L55

**Comment by glasgo-seven** [comment]
[Да.](https://memepedia.ru/wp-content/uploads/2019/11/nordic-gamer-meme-1.jpg)

**Comment by RB387** [comment]
OK.
